// Code generated by qtc from "default.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/http/views/layout/default.qtpl:1
package layout

//line internal/http/views/layout/default.qtpl:1
import (
	"github.com/gin-gonic/gin"
	"web/internal/bootstrap"
)

//line internal/http/views/layout/default.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/http/views/layout/default.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/http/views/layout/default.qtpl:7
type Page interface {
//line internal/http/views/layout/default.qtpl:7
	Lang() string
//line internal/http/views/layout/default.qtpl:7
	StreamLang(qw422016 *qt422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	WriteLang(qq422016 qtio422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	Title() string
//line internal/http/views/layout/default.qtpl:7
	StreamTitle(qw422016 *qt422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	WriteTitle(qq422016 qtio422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	SEO() string
//line internal/http/views/layout/default.qtpl:7
	StreamSEO(qw422016 *qt422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	WriteSEO(qq422016 qtio422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	CSS() string
//line internal/http/views/layout/default.qtpl:7
	StreamCSS(qw422016 *qt422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	WriteCSS(qq422016 qtio422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	Header() string
//line internal/http/views/layout/default.qtpl:7
	StreamHeader(qw422016 *qt422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	WriteHeader(qq422016 qtio422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	Sidebar() string
//line internal/http/views/layout/default.qtpl:7
	StreamSidebar(qw422016 *qt422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	WriteSidebar(qq422016 qtio422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	Content() string
//line internal/http/views/layout/default.qtpl:7
	StreamContent(qw422016 *qt422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	WriteContent(qq422016 qtio422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	Footer() string
//line internal/http/views/layout/default.qtpl:7
	StreamFooter(qw422016 *qt422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	WriteFooter(qq422016 qtio422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	Script() string
//line internal/http/views/layout/default.qtpl:7
	StreamScript(qw422016 *qt422016.Writer)
//line internal/http/views/layout/default.qtpl:7
	WriteScript(qq422016 qtio422016.Writer)
//line internal/http/views/layout/default.qtpl:7
}

// Page prints a page implementing Page interface.

//line internal/http/views/layout/default.qtpl:22
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line internal/http/views/layout/default.qtpl:22
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="`)
//line internal/http/views/layout/default.qtpl:24
	qw422016.N().S(p.Lang())
//line internal/http/views/layout/default.qtpl:24
	qw422016.N().S(`">
	<head>
        <title>`)
//line internal/http/views/layout/default.qtpl:26
	p.StreamTitle(qw422016)
//line internal/http/views/layout/default.qtpl:26
	qw422016.N().S(`</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta charset="utf-8" >
        <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
        <link rel="icon" type="image/png" href="/assets/images/logo.png" />
        `)
//line internal/http/views/layout/default.qtpl:31
	p.StreamSEO(qw422016)
//line internal/http/views/layout/default.qtpl:31
	qw422016.N().S(`

        `)
//line internal/http/views/layout/default.qtpl:33
	p.StreamCSS(qw422016)
//line internal/http/views/layout/default.qtpl:33
	qw422016.N().S(`
    </head>
	<body>
        <div class="loader-bg">
            <div class="loader-bar"></div>
        </div>
        <div id="pcoded" class="pcoded">
            <div class="pcoded-overlay-box"></div>
            <div class="pcoded-container navbar-wrapper">
                `)
//line internal/http/views/layout/default.qtpl:42
	p.StreamHeader(qw422016)
//line internal/http/views/layout/default.qtpl:42
	qw422016.N().S(`

                <div class="pcoded-main-container">
                    <div class="pcoded-wrapper">
                        `)
//line internal/http/views/layout/default.qtpl:46
	p.StreamSidebar(qw422016)
//line internal/http/views/layout/default.qtpl:46
	qw422016.N().S(`
                        
                        `)
//line internal/http/views/layout/default.qtpl:48
	p.StreamContent(qw422016)
//line internal/http/views/layout/default.qtpl:48
	qw422016.N().S(`
                    </div>
                </div>
            </div>
        </div>
        `)
//line internal/http/views/layout/default.qtpl:53
	p.StreamScript(qw422016)
//line internal/http/views/layout/default.qtpl:53
	qw422016.N().S(`
	</body>
</html>
`)
//line internal/http/views/layout/default.qtpl:56
}

//line internal/http/views/layout/default.qtpl:56
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line internal/http/views/layout/default.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/default.qtpl:56
	StreamPageTemplate(qw422016, p)
//line internal/http/views/layout/default.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/default.qtpl:56
}

//line internal/http/views/layout/default.qtpl:56
func PageTemplate(p Page) string {
//line internal/http/views/layout/default.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/default.qtpl:56
	WritePageTemplate(qb422016, p)
//line internal/http/views/layout/default.qtpl:56
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/default.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/default.qtpl:56
	return qs422016
//line internal/http/views/layout/default.qtpl:56
}

//line internal/http/views/layout/default.qtpl:59
type BasePage struct {
	Context *gin.Context
}

//line internal/http/views/layout/default.qtpl:63
func (p *BasePage) StreamLang(qw422016 *qt422016.Writer) {
//line internal/http/views/layout/default.qtpl:63
	qw422016.N().S(p.Context.GetString("lang"))
//line internal/http/views/layout/default.qtpl:63
}

//line internal/http/views/layout/default.qtpl:63
func (p *BasePage) WriteLang(qq422016 qtio422016.Writer) {
//line internal/http/views/layout/default.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/default.qtpl:63
	p.StreamLang(qw422016)
//line internal/http/views/layout/default.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/default.qtpl:63
}

//line internal/http/views/layout/default.qtpl:63
func (p *BasePage) Lang() string {
//line internal/http/views/layout/default.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/default.qtpl:63
	p.WriteLang(qb422016)
//line internal/http/views/layout/default.qtpl:63
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/default.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/default.qtpl:63
	return qs422016
//line internal/http/views/layout/default.qtpl:63
}

//line internal/http/views/layout/default.qtpl:64
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/http/views/layout/default.qtpl:64
}

//line internal/http/views/layout/default.qtpl:64
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/http/views/layout/default.qtpl:64
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/default.qtpl:64
	p.StreamTitle(qw422016)
//line internal/http/views/layout/default.qtpl:64
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/default.qtpl:64
}

//line internal/http/views/layout/default.qtpl:64
func (p *BasePage) Title() string {
//line internal/http/views/layout/default.qtpl:64
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/default.qtpl:64
	p.WriteTitle(qb422016)
//line internal/http/views/layout/default.qtpl:64
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/default.qtpl:64
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/default.qtpl:64
	return qs422016
//line internal/http/views/layout/default.qtpl:64
}

//line internal/http/views/layout/default.qtpl:65
func (p *BasePage) StreamSEO(qw422016 *qt422016.Writer) {
//line internal/http/views/layout/default.qtpl:65
}

//line internal/http/views/layout/default.qtpl:65
func (p *BasePage) WriteSEO(qq422016 qtio422016.Writer) {
//line internal/http/views/layout/default.qtpl:65
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/default.qtpl:65
	p.StreamSEO(qw422016)
//line internal/http/views/layout/default.qtpl:65
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/default.qtpl:65
}

//line internal/http/views/layout/default.qtpl:65
func (p *BasePage) SEO() string {
//line internal/http/views/layout/default.qtpl:65
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/default.qtpl:65
	p.WriteSEO(qb422016)
//line internal/http/views/layout/default.qtpl:65
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/default.qtpl:65
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/default.qtpl:65
	return qs422016
//line internal/http/views/layout/default.qtpl:65
}

//line internal/http/views/layout/default.qtpl:66
func (p *BasePage) StreamCSS(qw422016 *qt422016.Writer, libs []string) {
//line internal/http/views/layout/default.qtpl:66
	qw422016.N().S(`
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:500,700" rel="stylesheet">
    <link rel="stylesheet" href="/assets/libs/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/libs/waves/waves.min.css">
    <link rel="stylesheet" href="/assets/libs/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="/assets/libs/icofont/icofont.min.css">
    `)
//line internal/http/views/layout/default.qtpl:73
	for _, l := range libs {
//line internal/http/views/layout/default.qtpl:73
		qw422016.N().S(`
        `)
//line internal/http/views/layout/default.qtpl:74
		qw422016.N().S(l)
//line internal/http/views/layout/default.qtpl:74
		qw422016.N().S(`
    `)
//line internal/http/views/layout/default.qtpl:75
	}
//line internal/http/views/layout/default.qtpl:75
	qw422016.N().S(`
    <link rel="stylesheet" href="/assets/libs/admindek/css/feather.css?v=`)
//line internal/http/views/layout/default.qtpl:76
	qw422016.E().S(bootstrap.Config.Version)
//line internal/http/views/layout/default.qtpl:76
	qw422016.N().S(`">
    <link rel="stylesheet" href="/assets/libs/admindek/css/style.css">
    <link rel="stylesheet" href="/assets/css/style.css?v=`)
//line internal/http/views/layout/default.qtpl:78
	qw422016.E().S(bootstrap.Config.Version)
//line internal/http/views/layout/default.qtpl:78
	qw422016.N().S(`">
`)
//line internal/http/views/layout/default.qtpl:79
}

//line internal/http/views/layout/default.qtpl:79
func (p *BasePage) WriteCSS(qq422016 qtio422016.Writer, libs []string) {
//line internal/http/views/layout/default.qtpl:79
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/default.qtpl:79
	p.StreamCSS(qw422016, libs)
//line internal/http/views/layout/default.qtpl:79
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/default.qtpl:79
}

//line internal/http/views/layout/default.qtpl:79
func (p *BasePage) CSS(libs []string) string {
//line internal/http/views/layout/default.qtpl:79
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/default.qtpl:79
	p.WriteCSS(qb422016, libs)
//line internal/http/views/layout/default.qtpl:79
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/default.qtpl:79
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/default.qtpl:79
	return qs422016
//line internal/http/views/layout/default.qtpl:79
}

//line internal/http/views/layout/default.qtpl:80
func (p *BasePage) StreamHeader(qw422016 *qt422016.Writer) {
//line internal/http/views/layout/default.qtpl:80
	StreamHeader(qw422016, p)
//line internal/http/views/layout/default.qtpl:80
}

//line internal/http/views/layout/default.qtpl:80
func (p *BasePage) WriteHeader(qq422016 qtio422016.Writer) {
//line internal/http/views/layout/default.qtpl:80
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/default.qtpl:80
	p.StreamHeader(qw422016)
//line internal/http/views/layout/default.qtpl:80
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/default.qtpl:80
}

//line internal/http/views/layout/default.qtpl:80
func (p *BasePage) Header() string {
//line internal/http/views/layout/default.qtpl:80
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/default.qtpl:80
	p.WriteHeader(qb422016)
//line internal/http/views/layout/default.qtpl:80
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/default.qtpl:80
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/default.qtpl:80
	return qs422016
//line internal/http/views/layout/default.qtpl:80
}

//line internal/http/views/layout/default.qtpl:81
func (p *BasePage) StreamSidebar(qw422016 *qt422016.Writer) {
//line internal/http/views/layout/default.qtpl:81
	StreamSidebar(qw422016, p)
//line internal/http/views/layout/default.qtpl:81
}

//line internal/http/views/layout/default.qtpl:81
func (p *BasePage) WriteSidebar(qq422016 qtio422016.Writer) {
//line internal/http/views/layout/default.qtpl:81
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/default.qtpl:81
	p.StreamSidebar(qw422016)
//line internal/http/views/layout/default.qtpl:81
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/default.qtpl:81
}

//line internal/http/views/layout/default.qtpl:81
func (p *BasePage) Sidebar() string {
//line internal/http/views/layout/default.qtpl:81
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/default.qtpl:81
	p.WriteSidebar(qb422016)
//line internal/http/views/layout/default.qtpl:81
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/default.qtpl:81
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/default.qtpl:81
	return qs422016
//line internal/http/views/layout/default.qtpl:81
}

//line internal/http/views/layout/default.qtpl:82
func (p *BasePage) StreamContent(qw422016 *qt422016.Writer) {
//line internal/http/views/layout/default.qtpl:82
}

//line internal/http/views/layout/default.qtpl:82
func (p *BasePage) WriteContent(qq422016 qtio422016.Writer) {
//line internal/http/views/layout/default.qtpl:82
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/default.qtpl:82
	p.StreamContent(qw422016)
//line internal/http/views/layout/default.qtpl:82
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/default.qtpl:82
}

//line internal/http/views/layout/default.qtpl:82
func (p *BasePage) Content() string {
//line internal/http/views/layout/default.qtpl:82
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/default.qtpl:82
	p.WriteContent(qb422016)
//line internal/http/views/layout/default.qtpl:82
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/default.qtpl:82
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/default.qtpl:82
	return qs422016
//line internal/http/views/layout/default.qtpl:82
}

//line internal/http/views/layout/default.qtpl:83
func (p *BasePage) StreamFooter(qw422016 *qt422016.Writer) {
//line internal/http/views/layout/default.qtpl:83
	StreamFooter(qw422016, p)
//line internal/http/views/layout/default.qtpl:83
}

//line internal/http/views/layout/default.qtpl:83
func (p *BasePage) WriteFooter(qq422016 qtio422016.Writer) {
//line internal/http/views/layout/default.qtpl:83
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/default.qtpl:83
	p.StreamFooter(qw422016)
//line internal/http/views/layout/default.qtpl:83
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/default.qtpl:83
}

//line internal/http/views/layout/default.qtpl:83
func (p *BasePage) Footer() string {
//line internal/http/views/layout/default.qtpl:83
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/default.qtpl:83
	p.WriteFooter(qb422016)
//line internal/http/views/layout/default.qtpl:83
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/default.qtpl:83
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/default.qtpl:83
	return qs422016
//line internal/http/views/layout/default.qtpl:83
}

//line internal/http/views/layout/default.qtpl:84
func (p *BasePage) StreamScript(qw422016 *qt422016.Writer, libs []string) {
//line internal/http/views/layout/default.qtpl:84
	qw422016.N().S(`
    <script type="text/javascript">
        const config = {
            apiAddress: '`)
//line internal/http/views/layout/default.qtpl:87
	qw422016.N().S(bootstrap.SharedConfig.APIGateway.HTTPAddress)
//line internal/http/views/layout/default.qtpl:87
	qw422016.N().S(`'
        };
    </script>
    <script src="/assets/libs/jquery/jquery.min.js"></script>
    <script src="/assets/libs/jquery-ui/jquery-ui.min.js"></script>
    <script src="/assets/libs/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/libs/waves/waves.min.js"></script>
    <script src="/assets/libs/rocket-loader/rocket-loader.min.js"></script>
    `)
//line internal/http/views/layout/default.qtpl:96
	for _, scr := range libs {
//line internal/http/views/layout/default.qtpl:96
		qw422016.N().S(`
        `)
//line internal/http/views/layout/default.qtpl:97
		qw422016.N().S(scr)
//line internal/http/views/layout/default.qtpl:97
		qw422016.N().S(`
    `)
//line internal/http/views/layout/default.qtpl:98
	}
//line internal/http/views/layout/default.qtpl:98
	qw422016.N().S(`
    <script src="/assets/libs/admindek/js/pcoded.min.js"></script>
    <script src="/assets/libs/admindek/js/vertical-layout.min.js"></script>
    <script src="/assets/libs/admindek/js/script.min.js"></script>
    <script src="/assets/js/main.js?v=`)
//line internal/http/views/layout/default.qtpl:102
	qw422016.E().S(bootstrap.Config.Version)
//line internal/http/views/layout/default.qtpl:102
	qw422016.N().S(`"></script>
`)
//line internal/http/views/layout/default.qtpl:103
}

//line internal/http/views/layout/default.qtpl:103
func (p *BasePage) WriteScript(qq422016 qtio422016.Writer, libs []string) {
//line internal/http/views/layout/default.qtpl:103
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/default.qtpl:103
	p.StreamScript(qw422016, libs)
//line internal/http/views/layout/default.qtpl:103
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/default.qtpl:103
}

//line internal/http/views/layout/default.qtpl:103
func (p *BasePage) Script(libs []string) string {
//line internal/http/views/layout/default.qtpl:103
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/default.qtpl:103
	p.WriteScript(qb422016, libs)
//line internal/http/views/layout/default.qtpl:103
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/default.qtpl:103
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/default.qtpl:103
	return qs422016
//line internal/http/views/layout/default.qtpl:103
}
