// Code generated by qtc from "sidebar.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/http/views/layout/sidebar.qtpl:1
package layout

//line internal/http/views/layout/sidebar.qtpl:1
import (
	"strings"
	"web/internal/config"
)

//line internal/http/views/layout/sidebar.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/http/views/layout/sidebar.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/http/views/layout/sidebar.qtpl:7
func StreamSidebar(qw422016 *qt422016.Writer, p *BasePage) {
//line internal/http/views/layout/sidebar.qtpl:9
	menuItems, _ := p.Context.Value("menuItems").([]*config.MenuItem)

//line internal/http/views/layout/sidebar.qtpl:10
	qw422016.N().S(`<nav class="pcoded-navbar"><div class="nav-list"><div class="pcoded-inner-navbar main-menu">`)
//line internal/http/views/layout/sidebar.qtpl:14
	qw422016.N().S(`<ul class="pcoded-item pcoded-left-item">`)
//line internal/http/views/layout/sidebar.qtpl:16
	for _, menuItem := range menuItems {
//line internal/http/views/layout/sidebar.qtpl:18
		if !menuItem.IsShow {
			continue
		}

//line internal/http/views/layout/sidebar.qtpl:22
		if len(menuItem.Children) > 0 {
//line internal/http/views/layout/sidebar.qtpl:24
			activeIndex := -1
			for i := 0; i < len(menuItem.Children); i++ {
				if strings.HasPrefix(p.Context.Request.URL.Path, menuItem.Children[i].Route) {
					activeIndex = i
					break
				}
			}

//line internal/http/views/layout/sidebar.qtpl:31
			qw422016.N().S(`<li class="pcoded-hasmenu`)
//line internal/http/views/layout/sidebar.qtpl:32
			if activeIndex >= 0 {
//line internal/http/views/layout/sidebar.qtpl:32
				qw422016.N().S(` `)
//line internal/http/views/layout/sidebar.qtpl:32
				qw422016.N().S(`active pcoded-trigger`)
//line internal/http/views/layout/sidebar.qtpl:32
			}
//line internal/http/views/layout/sidebar.qtpl:32
			qw422016.N().S(`"><a href="javascript:void(0)" class="waves-effect waves-dark"><span class="pcoded-micon"><i class="`)
//line internal/http/views/layout/sidebar.qtpl:34
			qw422016.E().S(menuItem.Icon)
//line internal/http/views/layout/sidebar.qtpl:34
			qw422016.N().S(`"></i></span><span class="pcoded-mtext">`)
//line internal/http/views/layout/sidebar.qtpl:35
			qw422016.E().S(menuItem.Name)
//line internal/http/views/layout/sidebar.qtpl:35
			qw422016.N().S(`</span></a><ul class="pcoded-submenu">`)
//line internal/http/views/layout/sidebar.qtpl:38
			for j, childItem := range menuItem.Children {
//line internal/http/views/layout/sidebar.qtpl:40
				if !childItem.IsShow {
					continue
				}

//line internal/http/views/layout/sidebar.qtpl:43
				qw422016.N().S(`<li class="`)
//line internal/http/views/layout/sidebar.qtpl:44
				if activeIndex == j {
//line internal/http/views/layout/sidebar.qtpl:44
					qw422016.N().S(`active`)
//line internal/http/views/layout/sidebar.qtpl:44
				}
//line internal/http/views/layout/sidebar.qtpl:44
				qw422016.N().S(`"><a href="`)
//line internal/http/views/layout/sidebar.qtpl:45
				qw422016.E().S(childItem.Route)
//line internal/http/views/layout/sidebar.qtpl:45
				qw422016.N().S(`" class="waves-effect waves-dark"><span class="pcoded-mtext">`)
//line internal/http/views/layout/sidebar.qtpl:46
				qw422016.E().S(childItem.Name)
//line internal/http/views/layout/sidebar.qtpl:46
				qw422016.N().S(`</span></a></li>`)
//line internal/http/views/layout/sidebar.qtpl:49
			}
//line internal/http/views/layout/sidebar.qtpl:49
			qw422016.N().S(`</ul></li>`)
//line internal/http/views/layout/sidebar.qtpl:52
		} else if len(menuItem.Route) > 0 && string(menuItem.Route[0]) != "#" {
//line internal/http/views/layout/sidebar.qtpl:54
			isActive := false
			if (menuItem.Route == "/" && p.Context.Request.URL.Path == "/") || (menuItem.Route != "/" && strings.Contains(p.Context.Request.URL.Path, menuItem.Route)) {
				isActive = true
			}

//line internal/http/views/layout/sidebar.qtpl:58
			qw422016.N().S(`<li class="`)
//line internal/http/views/layout/sidebar.qtpl:59
			if isActive {
//line internal/http/views/layout/sidebar.qtpl:59
				qw422016.N().S(`active`)
//line internal/http/views/layout/sidebar.qtpl:59
			}
//line internal/http/views/layout/sidebar.qtpl:59
			qw422016.N().S(`"><a href="`)
//line internal/http/views/layout/sidebar.qtpl:60
			qw422016.E().S(menuItem.Route)
//line internal/http/views/layout/sidebar.qtpl:60
			qw422016.N().S(`" class="waves-effect waves-dark"><span class="pcoded-micon"><i class="`)
//line internal/http/views/layout/sidebar.qtpl:62
			qw422016.E().S(menuItem.Icon)
//line internal/http/views/layout/sidebar.qtpl:62
			qw422016.N().S(`"></i></span><span class="pcoded-mtext">`)
//line internal/http/views/layout/sidebar.qtpl:64
			qw422016.E().S(menuItem.Name)
//line internal/http/views/layout/sidebar.qtpl:64
			qw422016.N().S(`</span></a></li>`)
//line internal/http/views/layout/sidebar.qtpl:67
		}
//line internal/http/views/layout/sidebar.qtpl:68
	}
//line internal/http/views/layout/sidebar.qtpl:68
	qw422016.N().S(`</ul></div></div></nav>`)
//line internal/http/views/layout/sidebar.qtpl:73
}

//line internal/http/views/layout/sidebar.qtpl:73
func WriteSidebar(qq422016 qtio422016.Writer, p *BasePage) {
//line internal/http/views/layout/sidebar.qtpl:73
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/sidebar.qtpl:73
	StreamSidebar(qw422016, p)
//line internal/http/views/layout/sidebar.qtpl:73
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/sidebar.qtpl:73
}

//line internal/http/views/layout/sidebar.qtpl:73
func Sidebar(p *BasePage) string {
//line internal/http/views/layout/sidebar.qtpl:73
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/sidebar.qtpl:73
	WriteSidebar(qb422016, p)
//line internal/http/views/layout/sidebar.qtpl:73
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/sidebar.qtpl:73
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/sidebar.qtpl:73
	return qs422016
//line internal/http/views/layout/sidebar.qtpl:73
}
