// Code generated by qtc from "filter.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/http/views/pages/staticpage/partials/filter.qtpl:2
package partials

//line internal/http/views/pages/staticpage/partials/filter.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/http/views/pages/staticpage/partials/filter.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/http/views/pages/staticpage/partials/filter.qtpl:2
func StreamFilter(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/partials/filter.qtpl:2
	qw422016.N().S(`<div id="filter" class="form collapse" role="form"><div class="row"><div class="col-lg-6 col-md-6"><div class="form-group"><input name="ids" class="form-control reset-filter-onchange" type="text" placeholder="ids: 1,2,3, ..."></div></div><div class="col-lg-6 col-md-6"><div class="form-group"><input name="title" class="form-control reset-filter-onchange" type="text" placeholder="Name"></div></div></div><div class="row"><div class="col-lg-6 col-md-6"><div class="form-group"><input name="slug" class="form-control reset-filter-onchange" type="text" placeholder="Slug"></div></div><div class="col-lg-6 col-md-6"><div class="form-group"><select class="form-control status-selection is-select2" name="statuses" default=""></select></div></div></div><div class="row"><div class="col-lg-12 col-md-12"><button id="apply-filter" type="submit" class="btn btn-primary"><i class="fa fa-check"></i>Apply</button></div></div><div class="pb-4" style="width:100%;display:block;"></div></div>`)
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
}

//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
func WriteFilter(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
	StreamFilter(qw422016)
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
}

//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
func Filter() string {
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
	WriteFilter(qb422016)
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
	return qs422016
//line internal/http/views/pages/staticpage/partials/filter.qtpl:37
}
