// Code generated by qtc from "dashboard.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/http/views/pages/dashboard/dashboard.qtpl:1
package dashboard

//line internal/http/views/pages/dashboard/dashboard.qtpl:1
import (
	"web/internal/http/views/layout"

//line internal/http/views/pages/dashboard/dashboard.qtpl:5

	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/http/views/pages/dashboard/dashboard.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/http/views/pages/dashboard/dashboard.qtpl:6
type DashboardIndex struct {
	layout.BasePage
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:12
func (p *DashboardIndex) streamgetSeoTitle(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:12
	qw422016.N().S(`Dashboard`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:14
func (p *DashboardIndex) writegetSeoTitle(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
	p.streamgetSeoTitle(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:14
func (p *DashboardIndex) getSeoTitle() string {
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
	p.writegetSeoTitle(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
	return qs422016
//line internal/http/views/pages/dashboard/dashboard.qtpl:14
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:18
func (p *DashboardIndex) streamgetSeoDesc(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:18
	qw422016.N().S(`This is seo desc`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:20
func (p *DashboardIndex) writegetSeoDesc(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
	p.streamgetSeoDesc(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:20
func (p *DashboardIndex) getSeoDesc() string {
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
	p.writegetSeoDesc(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
	return qs422016
//line internal/http/views/pages/dashboard/dashboard.qtpl:20
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:24
func (p *DashboardIndex) streamgetSeoKW(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:24
	qw422016.N().S(`This is seo keyword`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:26
func (p *DashboardIndex) writegetSeoKW(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
	p.streamgetSeoKW(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:26
func (p *DashboardIndex) getSeoKW() string {
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
	p.writegetSeoKW(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
	return qs422016
//line internal/http/views/pages/dashboard/dashboard.qtpl:26
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:29
func (p *DashboardIndex) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
	qw422016.N().S(p.getSeoTitle())
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:29
func (p *DashboardIndex) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
	p.StreamTitle(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:29
func (p *DashboardIndex) Title() string {
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
	p.WriteTitle(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
	return qs422016
//line internal/http/views/pages/dashboard/dashboard.qtpl:29
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:31
func (p *DashboardIndex) StreamSeo(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:31
	qw422016.N().S(`
	`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:32
	p.BasePage.StreamSeo(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:32
	qw422016.N().S(`
	<meta name="title" content="`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:33
	qw422016.N().S(p.getSeoTitle())
//line internal/http/views/pages/dashboard/dashboard.qtpl:33
	qw422016.N().S(`">
`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:34
func (p *DashboardIndex) WriteSeo(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
	p.StreamSeo(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:34
func (p *DashboardIndex) Seo() string {
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
	p.WriteSeo(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
	return qs422016
//line internal/http/views/pages/dashboard/dashboard.qtpl:34
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:37
func (p *DashboardIndex) StreamCss(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:38
	p.BasePage.StreamCss(qw422016, []string{
		"<link rel=\"stylesheet\" href=\"/assets/libs/bootstrap-table/bootstrap-table.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/select2/css/select2.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/toastr/toastr.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/sweetalert2/sweetalert2.min.css\">",
	})
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:44
func (p *DashboardIndex) WriteCss(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
	p.StreamCss(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:44
func (p *DashboardIndex) Css() string {
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
	p.WriteCss(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
	return qs422016
//line internal/http/views/pages/dashboard/dashboard.qtpl:44
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:47
func (p *DashboardIndex) StreamScript(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:47
	qw422016.N().S(`
	`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:48
	p.BasePage.StreamScript(qw422016, []string{
		"<script src=\"/assets/libs/bootstrap-table/bootstrap-table.min.js\"></script>",
		"<script src=\"/assets/libs/ckeditor/ckeditor.js\"></script>",
		"<script src=\"/assets/libs/select2/js/select2.min.js\"></script>",
		"<script src=\"/assets/libs/toastr/toastr.min.js\"></script>",
		"<script src=\"/assets/libs/sweetalert2/sweetalert2.min.js\"></script>",
	})
//line internal/http/views/pages/dashboard/dashboard.qtpl:54
	qw422016.N().S(`
	<script type="text/javascript">
		`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:56
	qw422016.N().S(`
	</script>
`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:58
func (p *DashboardIndex) WriteScript(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
	p.StreamScript(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:58
func (p *DashboardIndex) Script() string {
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
	p.WriteScript(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
	return qs422016
//line internal/http/views/pages/dashboard/dashboard.qtpl:58
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:61
func (p *DashboardIndex) StreamContent(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:61
	qw422016.N().S(`<div class="pcoded-content"><div class="page-header card"><div class="row align-items-end"><div class="col-lg-8"><div class="page-header-title"><i class="feather icon-home bg-c-blue"></i><div class="d-inline"><h5>Dashboard</h5><span>Some overview data.</span></div></div></div><div class="col-lg-4"><div class="page-header-breadcrumb"><ul class=" breadcrumb breadcrumb-title"><li class="breadcrumb-item"><a href="#!"><i class="feather icon-home"></i>`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:78
	qw422016.N().S(` `)
//line internal/http/views/pages/dashboard/dashboard.qtpl:78
	qw422016.N().S(`Dashboard</a></li></ul></div></div></div></div><div class="pcoded-inner-content"><div class="main-body"><div class="page-wrapper"><div class="page-body"><div class="row"><div class="col-md-12 col-xl-12"><div class="card sale-card"><div class="card-header"><h5>Dashboard first card block</h5></div><div class="card-block"><h1>Some overview data will be displayed here!</h1></div></div></div></div></div></div></div></div></div>`)
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:108
func (p *DashboardIndex) WriteContent(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
	p.StreamContent(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
}

//line internal/http/views/pages/dashboard/dashboard.qtpl:108
func (p *DashboardIndex) Content() string {
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
	p.WriteContent(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
	return qs422016
//line internal/http/views/pages/dashboard/dashboard.qtpl:108
}
