// Code generated by qtc from "form.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/http/views/pages/staticpage/partials/form.qtpl:1
package partials

//line internal/http/views/pages/staticpage/partials/form.qtpl:1
import (
	"shared/models/staticpagemodel"
)

//line internal/http/views/pages/staticpage/partials/form.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/http/views/pages/staticpage/partials/form.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/http/views/pages/staticpage/partials/form.qtpl:6
func StreamForm(qw422016 *qt422016.Writer, model *staticpagemodel.StaticPage) {
//line internal/http/views/pages/staticpage/partials/form.qtpl:6
	qw422016.N().S(`<ul class="nav nav-tabs md-tabs tab-icon mb-0" role="tablist"><li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#main" role="tab"><i class="icofont icofont-home"></i>Main</a><div class="slide"></div></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#seo" role="tab"><i class="icofont icofont-globe"></i>Seo</a><div class="slide"></div></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#config" role="tab"><i class="icofont icofont-gears"></i>Config</a><div class="slide"></div></li></ul><form id="static-page-form" class="form form-`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:27
	if model != nil {
//line internal/http/views/pages/staticpage/partials/form.qtpl:27
		qw422016.N().S(`update`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:27
	} else {
//line internal/http/views/pages/staticpage/partials/form.qtpl:27
		qw422016.N().S(`create`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:27
	}
//line internal/http/views/pages/staticpage/partials/form.qtpl:27
	qw422016.N().S(` `)
//line internal/http/views/pages/staticpage/partials/form.qtpl:27
	qw422016.N().S(`tab-content card-block pb-0"><div class="general-errs"></div><div id="main" class="tab-pane active" role="tabpanel"><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label" for="title">Title<span class="text-danger">*</span>:</label><input name="title" value="`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:35
	if model != nil {
//line internal/http/views/pages/staticpage/partials/form.qtpl:35
		qw422016.E().S(model.Title)
//line internal/http/views/pages/staticpage/partials/form.qtpl:35
	}
//line internal/http/views/pages/staticpage/partials/form.qtpl:35
	qw422016.N().S(`" type="text" class="form-control" autocomplete="off" onkeyup="toSlug(this, `)
//line internal/http/views/pages/staticpage/partials/form.qtpl:35
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/partials/form.qtpl:35
	qw422016.N().S(`#static-page-form input[name='slug']`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:35
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/partials/form.qtpl:35
	qw422016.N().S(`)" /></div></div></div><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label" for="slug">Slug<span class="text-danger">*</span>:</label><input name="slug" value="`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:43
	if model != nil {
//line internal/http/views/pages/staticpage/partials/form.qtpl:43
		qw422016.E().S(model.Slug)
//line internal/http/views/pages/staticpage/partials/form.qtpl:43
	}
//line internal/http/views/pages/staticpage/partials/form.qtpl:43
	qw422016.N().S(`" type="text" class="form-control" autocomplete="off" /></div></div></div><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label" for="sortOrder">Sort Order:</label><input name="sortOrder" value="`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:51
	if model != nil {
//line internal/http/views/pages/staticpage/partials/form.qtpl:51
		qw422016.N().D(int(model.SortOrder))
//line internal/http/views/pages/staticpage/partials/form.qtpl:51
	}
//line internal/http/views/pages/staticpage/partials/form.qtpl:51
	qw422016.N().S(`" type="number" class="form-control" autocomplete="off" /></div></div></div><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label" for="content">Content:</label><textarea name="content" class="form-control">`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:59
	if model != nil {
//line internal/http/views/pages/staticpage/partials/form.qtpl:59
		qw422016.E().S(model.Content)
//line internal/http/views/pages/staticpage/partials/form.qtpl:59
	}
//line internal/http/views/pages/staticpage/partials/form.qtpl:59
	qw422016.N().S(`</textarea></div></div></div><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label d-block" for="pageType">Page Type:</label><select class="form-control page-type-selection is-select2" name="pageType"></select></div></div></div><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label d-block" for="status">Status:</label><select class="form-control status-selection is-select2" name="status"></select></div></div></div></div><div id="seo" class="tab-pane" role="tabpanel"><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label" for="metaTitle">Meta Title:</label><input name="metaTitle" value="`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:87
	if model != nil && model.Seo != nil {
//line internal/http/views/pages/staticpage/partials/form.qtpl:87
		qw422016.E().S(model.Seo.MetaTitle)
//line internal/http/views/pages/staticpage/partials/form.qtpl:87
	}
//line internal/http/views/pages/staticpage/partials/form.qtpl:87
	qw422016.N().S(`" default="" type="text" class="form-control" autocomplete="off" /></div></div></div><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label" for="metaDescription">Meta Description:</label><textarea name="metaDescription" default="" class="form-control" autocomplete="off">`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:95
	if model != nil && model.Seo != nil {
//line internal/http/views/pages/staticpage/partials/form.qtpl:95
		qw422016.E().S(model.Seo.MetaDesc)
//line internal/http/views/pages/staticpage/partials/form.qtpl:95
	}
//line internal/http/views/pages/staticpage/partials/form.qtpl:95
	qw422016.N().S(`</textarea></div></div></div><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label" for="metaKeywords">Meta Keywords:</label><textarea name="metaKeywords" default="" class="form-control" autocomplete="off"></textarea>`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:104
	qw422016.N().S(`</div></div></div><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label" for="schema">Schema:</label><textarea name="schema" default="" class="form-control" autocomplete="off">`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:112
	if model != nil && model.Seo != nil {
//line internal/http/views/pages/staticpage/partials/form.qtpl:112
		qw422016.E().S(model.Seo.Schema)
//line internal/http/views/pages/staticpage/partials/form.qtpl:112
	}
//line internal/http/views/pages/staticpage/partials/form.qtpl:112
	qw422016.N().S(`</textarea></div></div></div></div><div id="config" class="tab-pane" role="tabpanel"><div class="card-header pl-0 pr-0"><h5>Ads Config</h5></div><div class="card-block pl-0 pr-0"><div class="row"><div class="col-lg-12 col-sm-12"><div class="form-group"><label class="col-form-label d-block" for="adsPlatform">Ads Platform:</label><select class="form-control ads-platform-selection is-select2" name="adsPlatform"></select></div></div></div></div></div><div class="row"><div class="col-lg-12 col-sm-12"><button class="btn btn-primary" type="submit"><i class="fa fa-paper-plane"></i>`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:135
	qw422016.N().S(` `)
//line internal/http/views/pages/staticpage/partials/form.qtpl:135
	qw422016.N().S(`Submit</button></div></div></form>`)
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
}

//line internal/http/views/pages/staticpage/partials/form.qtpl:139
func WriteForm(qq422016 qtio422016.Writer, model *staticpagemodel.StaticPage) {
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
	StreamForm(qw422016, model)
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
}

//line internal/http/views/pages/staticpage/partials/form.qtpl:139
func Form(model *staticpagemodel.StaticPage) string {
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
	WriteForm(qb422016, model)
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
	return qs422016
//line internal/http/views/pages/staticpage/partials/form.qtpl:139
}
