// Code generated by qtc from "update.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/http/views/pages/staticpage/update.qtpl:1
package staticpage

//line internal/http/views/pages/staticpage/update.qtpl:1
import (
	"shared/models/staticpagemodel"
	"web/internal/bootstrap"
	"web/internal/http/views/layout"
	"web/internal/http/views/pages/staticpage/partials"
)

//line internal/http/views/pages/staticpage/update.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/http/views/pages/staticpage/update.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/http/views/pages/staticpage/update.qtpl:9
type Update struct {
	layout.BasePage
	StaticPage *staticpagemodel.StaticPage
	Errs       map[string]string
}

//line internal/http/views/pages/staticpage/update.qtpl:17
func (p *Update) streamgetSEOTitle(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:17
	qw422016.N().S(`Update static page`)
//line internal/http/views/pages/staticpage/update.qtpl:19
}

//line internal/http/views/pages/staticpage/update.qtpl:19
func (p *Update) writegetSEOTitle(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/update.qtpl:19
	p.streamgetSEOTitle(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:19
}

//line internal/http/views/pages/staticpage/update.qtpl:19
func (p *Update) getSEOTitle() string {
//line internal/http/views/pages/staticpage/update.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/update.qtpl:19
	p.writegetSEOTitle(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:19
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/update.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:19
	return qs422016
//line internal/http/views/pages/staticpage/update.qtpl:19
}

//line internal/http/views/pages/staticpage/update.qtpl:23
func (p *Update) streamgetSEODescription(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:23
	qw422016.N().S(`This is seo desc`)
//line internal/http/views/pages/staticpage/update.qtpl:25
}

//line internal/http/views/pages/staticpage/update.qtpl:25
func (p *Update) writegetSEODescription(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/update.qtpl:25
	p.streamgetSEODescription(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:25
}

//line internal/http/views/pages/staticpage/update.qtpl:25
func (p *Update) getSEODescription() string {
//line internal/http/views/pages/staticpage/update.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/update.qtpl:25
	p.writegetSEODescription(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:25
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/update.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:25
	return qs422016
//line internal/http/views/pages/staticpage/update.qtpl:25
}

//line internal/http/views/pages/staticpage/update.qtpl:29
func (p *Update) streamgetSEOKeywords(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:29
	qw422016.N().S(`This is seo keyword`)
//line internal/http/views/pages/staticpage/update.qtpl:31
}

//line internal/http/views/pages/staticpage/update.qtpl:31
func (p *Update) writegetSEOKeywords(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/update.qtpl:31
	p.streamgetSEOKeywords(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:31
}

//line internal/http/views/pages/staticpage/update.qtpl:31
func (p *Update) getSEOKeywords() string {
//line internal/http/views/pages/staticpage/update.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/update.qtpl:31
	p.writegetSEOKeywords(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:31
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/update.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:31
	return qs422016
//line internal/http/views/pages/staticpage/update.qtpl:31
}

//line internal/http/views/pages/staticpage/update.qtpl:34
func (p *Update) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:34
	qw422016.N().S(p.getSEOTitle())
//line internal/http/views/pages/staticpage/update.qtpl:34
}

//line internal/http/views/pages/staticpage/update.qtpl:34
func (p *Update) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/update.qtpl:34
	p.StreamTitle(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:34
}

//line internal/http/views/pages/staticpage/update.qtpl:34
func (p *Update) Title() string {
//line internal/http/views/pages/staticpage/update.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/update.qtpl:34
	p.WriteTitle(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:34
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/update.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:34
	return qs422016
//line internal/http/views/pages/staticpage/update.qtpl:34
}

//line internal/http/views/pages/staticpage/update.qtpl:36
func (p *Update) StreamSEO(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:36
	qw422016.N().S(`
	`)
//line internal/http/views/pages/staticpage/update.qtpl:37
	p.BasePage.StreamSEO(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:37
	qw422016.N().S(`
	<meta name="title" content="`)
//line internal/http/views/pages/staticpage/update.qtpl:38
	qw422016.N().S(p.getSEOTitle())
//line internal/http/views/pages/staticpage/update.qtpl:38
	qw422016.N().S(`">
`)
//line internal/http/views/pages/staticpage/update.qtpl:39
}

//line internal/http/views/pages/staticpage/update.qtpl:39
func (p *Update) WriteSEO(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/update.qtpl:39
	p.StreamSEO(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:39
}

//line internal/http/views/pages/staticpage/update.qtpl:39
func (p *Update) SEO() string {
//line internal/http/views/pages/staticpage/update.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/update.qtpl:39
	p.WriteSEO(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:39
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/update.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:39
	return qs422016
//line internal/http/views/pages/staticpage/update.qtpl:39
}

//line internal/http/views/pages/staticpage/update.qtpl:42
func (p *Update) StreamCSS(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:43
	p.BasePage.StreamCSS(qw422016, []string{
		"<link rel=\"stylesheet\" href=\"/assets/libs/select2/css/select2.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/toastr/toastr.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/icheck/skins/square/green.css\">",
	})
//line internal/http/views/pages/staticpage/update.qtpl:48
}

//line internal/http/views/pages/staticpage/update.qtpl:48
func (p *Update) WriteCSS(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/update.qtpl:48
	p.StreamCSS(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:48
}

//line internal/http/views/pages/staticpage/update.qtpl:48
func (p *Update) CSS() string {
//line internal/http/views/pages/staticpage/update.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/update.qtpl:48
	p.WriteCSS(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:48
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/update.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:48
	return qs422016
//line internal/http/views/pages/staticpage/update.qtpl:48
}

//line internal/http/views/pages/staticpage/update.qtpl:51
func (p *Update) StreamScript(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:51
	qw422016.N().S(`
	`)
//line internal/http/views/pages/staticpage/update.qtpl:52
	p.BasePage.StreamScript(qw422016, []string{
		"<script src=\"/assets/libs/select2/js/select2.min.js\"></script>",
		"<script src=\"/assets/libs/toastr/toastr.min.js\"></script>",
		"<script src=\"/assets/libs/ckeditor/ckeditor.js\"></script>",
		"<script src=\"/assets/libs/icheck/icheck.min.js\"></script>",
		"<script src=\"/assets/libs/slugify/slugify.js\"></script>",
	})
//line internal/http/views/pages/staticpage/update.qtpl:58
	qw422016.N().S(`
	<script type="text/javascript">
		toastr.options.closeButton = true;
		toastr.options.progressBar = true;

		const trans = {};

		`)
//line internal/http/views/pages/staticpage/update.qtpl:65
	qw422016.N().S(`function getFormData($form) {
    var formData = $form.serializeArray()
        .reduce(function (json, { name, value }) {
            json[name] = value;
            return json;
        }, {});

    return {
        title: formData.title || '',
        slug: formData.slug || '',
        sortOrder: parseInt(formData.sortOrder) || 0,
        content: CKEDITOR.instances.content.getData(),
        pageType: parseInt(formData.pageType) || 0,
        seo: {
            metaTitle: formData.metaTitle || '',
            metaDesc: formData.metaDes || '',
            metaKeywords: formData.metaKeywords || '',
            schema: formData.schema || '',
        },
        adsPlatform: parseInt(formData.adsPlatform) || 0,
        status: parseInt(formData.status) || 0
    }
}

$(function () {
    CKEDITOR.replace('content', {
        toolbarGroups: [
            { name: 'document', groups: ['mode', 'document', 'doctools'] },
            { name: 'clipboard', groups: ['clipboard', 'undo'] },
            { name: 'editing', groups: ['find', 'selection', 'spellchecker', 'editing'] },
            { name: 'forms', groups: ['forms'] },
            '/',
            { name: 'basicstyles', groups: ['basicstyles', 'cleanup'] },
            { name: 'paragraph', groups: ['list', 'indent', 'blocks', 'align', 'bidi', 'paragraph'] },
            { name: 'links', groups: ['links'] },
            { name: 'insert', groups: ['insert'] },
            '/',
            { name: 'styles', groups: ['styles'] },
            { name: 'colors', groups: ['colors'] },
            { name: 'tools', groups: ['tools'] },
            { name: 'others', groups: ['others'] },
            { name: 'about', groups: ['about'] }
        ],
        removeButtons: 'Save,NewPage,Templates,PasteText,PasteFromWord,ImageButton,Button,Select,Textarea,TextField,Form,Checkbox,Radio,HiddenField,CopyFormatting,RemoveFormat,Subscript,Language,BidiRtl,BidiLtr,Flash,PageBreak,Iframe,Font,ShowBlocks,About',
        filebrowserBrowseUrl: '/media/file-manager?sf=/content/page',
        filebrowserUploadUrl: '/media/editor-upload-file?sf=/content/page',
        height: '500px',
        on: {
            instanceReady: function () {
                const dtd = CKEDITOR.dtd;
    
                for ( var e in CKEDITOR.tools.extend( {}, 
                    dtd.$block, 
                    dtd.$listItem, 
                    dtd.$tableContent ) 
                ) {
                    this.dataProcessor.writer.setRules( e, {
                        indent: false,
                        breakBeforeOpen: false,
                        breakAfterOpen: false,
                        breakBeforeClose: false,
                        breakAfterClose: false
                    });
                }
            }
        }
    });

    $('#static-page-form .status-selection').select2({
        width: '100%',
        allowClear: false,
        minimumResultsForSearch: Infinity,
        placeholder: 'Select status',
        dropdownParent: $('#static-page-form'),
    });

    $('#static-page-form .page-type-selection').select2({
        width: '100%',
        allowClear: false,
        minimumResultsForSearch: Infinity,
        placeholder: 'Select page type',
        dropdownParent: $('#static-page-form')
    });

    $('#static-page-form .ads-platform-selection').select2({
        width: '100%',
        allowClear: false,
        minimumResultsForSearch: Infinity,
        placeholder: 'Select Ads Platform',
        dropdownParent: $('#static-page-form')
    });
});`)
//line internal/http/views/pages/staticpage/update.qtpl:65
	qw422016.N().S(`
		`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`$(function () {
    $('#static-page-form.form-update').submit(function (event) {
        event.preventDefault();

        const id = $(this).find('input[name="id"][type="hidden"]').val();

        const formData = getFormData($(this));    
        formData.fields = Object.keys(formData);

    
        $.ajax({
            type: 'POST',
            url: `)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`${config.apiAddress}/v1/staticPages/${id}/update`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`,
            authRequired: true,          // 👈 marks this request for interception
            xhrFields: { withCredentials: true },
            crossDomain: true,
            data: JSON.stringify(formData),
            success: function (data) {
                toastr['success'](`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`A new page was created successfully!`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`);
                window.location.replace('/staticPages');
            },
            error: function (xhr, status, error) {
                const resJson = xhr.responseJSON || {};
                const errors = resJson.data || {};
                errors.forEach(e => {
                    const { field, message } = e;

                    // Escape special characters for jQuery attribute selector
                    const safeField = field.replace(/([!"#$%&'()*+,./:;<=>?@[\\\]^`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`{|}~])/g, "\\$1");

                    const $input = $('#static-page-form').find(`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`[name="${safeField}"]`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`).first();

                    if ($input.length) {
                        addFieldError($input, message);
                    } else {
                        console.warn(`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`Field not found: ${field}`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`);
                    }
                });

                toastr['error'](resJson.message || `)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`An error occurred!`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`);
            },
            contentType: 'application/json',
            dataType: 'json'
        });
    
        return false;
    });
});`)
//line internal/http/views/pages/staticpage/update.qtpl:66
	qw422016.N().S(`
	</script>
`)
//line internal/http/views/pages/staticpage/update.qtpl:68
}

//line internal/http/views/pages/staticpage/update.qtpl:68
func (p *Update) WriteScript(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:68
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/update.qtpl:68
	p.StreamScript(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:68
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:68
}

//line internal/http/views/pages/staticpage/update.qtpl:68
func (p *Update) Script() string {
//line internal/http/views/pages/staticpage/update.qtpl:68
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/update.qtpl:68
	p.WriteScript(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:68
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/update.qtpl:68
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:68
	return qs422016
//line internal/http/views/pages/staticpage/update.qtpl:68
}

//line internal/http/views/pages/staticpage/update.qtpl:71
func (p *Update) StreamContent(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:71
	qw422016.N().S(`<div class="pcoded-content"><div class="page-header card"><div class="row align-items-end"><div class="col-lg-8"><div class="page-header-title"><i class="feather icon-home bg-c-blue"></i><div class="d-inline"><h5>`)
//line internal/http/views/pages/staticpage/update.qtpl:79
	qw422016.E().S(bootstrap.Translator.T(p.Lang(), "UPDATE", nil))
//line internal/http/views/pages/staticpage/update.qtpl:79
	qw422016.N().S(`</h5><span class="icofont icofont-dog"></span></div></div></div><div class="col-lg-4"><div class="page-header-breadcrumb"><ul class=" breadcrumb breadcrumb-title"><li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i>`)
//line internal/http/views/pages/staticpage/update.qtpl:88
	qw422016.N().S(` `)
//line internal/http/views/pages/staticpage/update.qtpl:88
	qw422016.E().S(bootstrap.Translator.T(p.Lang(), "DASHBOARD", nil))
//line internal/http/views/pages/staticpage/update.qtpl:88
	qw422016.N().S(`</a></li><li class="breadcrumb-item"><a href="/staticPages">`)
//line internal/http/views/pages/staticpage/update.qtpl:90
	qw422016.E().S(bootstrap.Translator.T(p.Lang(), "STATIC_PAGES", nil))
//line internal/http/views/pages/staticpage/update.qtpl:90
	qw422016.N().S(`</a></li><li class="breadcrumb-item"><a href="#!">`)
//line internal/http/views/pages/staticpage/update.qtpl:91
	qw422016.E().S(bootstrap.Translator.T(p.Lang(), "UPDATE", nil))
//line internal/http/views/pages/staticpage/update.qtpl:91
	qw422016.N().S(`</a></li></ul></div></div></div></div><div class="pcoded-inner-content"><div class="main-body"><div class="page-wrapper"><div class="page-body"><div class="row"><div class="col-md-12 col-xl-12"><div class="card sale-card"><div class="card-block">`)
//line internal/http/views/pages/staticpage/update.qtpl:105
	partials.StreamForm(qw422016, p.StaticPage, p.Lang())
//line internal/http/views/pages/staticpage/update.qtpl:105
	qw422016.N().S(`</div></div></div></div></div></div></div></div></div>`)
//line internal/http/views/pages/staticpage/update.qtpl:115
}

//line internal/http/views/pages/staticpage/update.qtpl:115
func (p *Update) WriteContent(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/update.qtpl:115
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/update.qtpl:115
	p.StreamContent(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:115
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/update.qtpl:115
}

//line internal/http/views/pages/staticpage/update.qtpl:115
func (p *Update) Content() string {
//line internal/http/views/pages/staticpage/update.qtpl:115
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/update.qtpl:115
	p.WriteContent(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:115
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/update.qtpl:115
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/update.qtpl:115
	return qs422016
//line internal/http/views/pages/staticpage/update.qtpl:115
}
