// Code generated by qtc from "create.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/http/views/pages/staticpage/create.qtpl:1
package staticpage

//line internal/http/views/pages/staticpage/create.qtpl:1
import (
	"cms/internal/bootstrap"
	"cms/internal/http/views/layout"
	"cms/internal/http/views/pages/staticpage/partials"
	"shared/models/staticpagemodel"
)

//line internal/http/views/pages/staticpage/create.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/http/views/pages/staticpage/create.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/http/views/pages/staticpage/create.qtpl:9
type Create struct {
	layout.BasePage
	StaticPage *staticpagemodel.StaticPage
	Errs       map[string]string
}

//line internal/http/views/pages/staticpage/create.qtpl:17
func (p *Create) streamgetSeoTitle(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:17
	qw422016.N().S(`Create new page`)
//line internal/http/views/pages/staticpage/create.qtpl:19
}

//line internal/http/views/pages/staticpage/create.qtpl:19
func (p *Create) writegetSeoTitle(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/create.qtpl:19
	p.streamgetSeoTitle(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:19
}

//line internal/http/views/pages/staticpage/create.qtpl:19
func (p *Create) getSeoTitle() string {
//line internal/http/views/pages/staticpage/create.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/create.qtpl:19
	p.writegetSeoTitle(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:19
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/create.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:19
	return qs422016
//line internal/http/views/pages/staticpage/create.qtpl:19
}

//line internal/http/views/pages/staticpage/create.qtpl:23
func (p *Create) streamgetSeoDesc(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:23
	qw422016.N().S(`This is seo desc`)
//line internal/http/views/pages/staticpage/create.qtpl:25
}

//line internal/http/views/pages/staticpage/create.qtpl:25
func (p *Create) writegetSeoDesc(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/create.qtpl:25
	p.streamgetSeoDesc(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:25
}

//line internal/http/views/pages/staticpage/create.qtpl:25
func (p *Create) getSeoDesc() string {
//line internal/http/views/pages/staticpage/create.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/create.qtpl:25
	p.writegetSeoDesc(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:25
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/create.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:25
	return qs422016
//line internal/http/views/pages/staticpage/create.qtpl:25
}

//line internal/http/views/pages/staticpage/create.qtpl:29
func (p *Create) streamgetSeoKW(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:29
	qw422016.N().S(`This is seo keyword`)
//line internal/http/views/pages/staticpage/create.qtpl:31
}

//line internal/http/views/pages/staticpage/create.qtpl:31
func (p *Create) writegetSeoKW(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/create.qtpl:31
	p.streamgetSeoKW(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:31
}

//line internal/http/views/pages/staticpage/create.qtpl:31
func (p *Create) getSeoKW() string {
//line internal/http/views/pages/staticpage/create.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/create.qtpl:31
	p.writegetSeoKW(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:31
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/create.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:31
	return qs422016
//line internal/http/views/pages/staticpage/create.qtpl:31
}

//line internal/http/views/pages/staticpage/create.qtpl:34
func (p *Create) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:34
	qw422016.N().S(p.getSeoTitle())
//line internal/http/views/pages/staticpage/create.qtpl:34
}

//line internal/http/views/pages/staticpage/create.qtpl:34
func (p *Create) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/create.qtpl:34
	p.StreamTitle(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:34
}

//line internal/http/views/pages/staticpage/create.qtpl:34
func (p *Create) Title() string {
//line internal/http/views/pages/staticpage/create.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/create.qtpl:34
	p.WriteTitle(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:34
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/create.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:34
	return qs422016
//line internal/http/views/pages/staticpage/create.qtpl:34
}

//line internal/http/views/pages/staticpage/create.qtpl:36
func (p *Create) StreamSeo(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:36
	qw422016.N().S(`
	`)
//line internal/http/views/pages/staticpage/create.qtpl:37
	p.BasePage.StreamSeo(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:37
	qw422016.N().S(`
	<meta name="title" content="`)
//line internal/http/views/pages/staticpage/create.qtpl:38
	qw422016.N().S(p.getSeoTitle())
//line internal/http/views/pages/staticpage/create.qtpl:38
	qw422016.N().S(`">
`)
//line internal/http/views/pages/staticpage/create.qtpl:39
}

//line internal/http/views/pages/staticpage/create.qtpl:39
func (p *Create) WriteSeo(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:39
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/create.qtpl:39
	p.StreamSeo(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:39
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:39
}

//line internal/http/views/pages/staticpage/create.qtpl:39
func (p *Create) Seo() string {
//line internal/http/views/pages/staticpage/create.qtpl:39
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/create.qtpl:39
	p.WriteSeo(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:39
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/create.qtpl:39
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:39
	return qs422016
//line internal/http/views/pages/staticpage/create.qtpl:39
}

//line internal/http/views/pages/staticpage/create.qtpl:42
func (p *Create) StreamCss(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:43
	p.BasePage.StreamCss(qw422016, []string{
		"<link rel=\"stylesheet\" href=\"/assets/libs/select2/css/select2.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/toastr/toastr.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/icheck/skins/square/green.css\">",
	})
//line internal/http/views/pages/staticpage/create.qtpl:48
}

//line internal/http/views/pages/staticpage/create.qtpl:48
func (p *Create) WriteCss(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/create.qtpl:48
	p.StreamCss(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:48
}

//line internal/http/views/pages/staticpage/create.qtpl:48
func (p *Create) Css() string {
//line internal/http/views/pages/staticpage/create.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/create.qtpl:48
	p.WriteCss(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:48
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/create.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:48
	return qs422016
//line internal/http/views/pages/staticpage/create.qtpl:48
}

//line internal/http/views/pages/staticpage/create.qtpl:51
func (p *Create) StreamScript(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:51
	qw422016.N().S(`
	`)
//line internal/http/views/pages/staticpage/create.qtpl:52
	p.BasePage.StreamScript(qw422016, []string{
		"<script src=\"/assets/libs/select2/js/select2.min.js\"></script>",
		"<script src=\"/assets/libs/toastr/toastr.min.js\"></script>",
		"<script src=\"/assets/libs/ckeditor/ckeditor.js\"></script>",
		"<script src=\"/assets/libs/icheck/icheck.min.js\"></script>",
		"<script src=\"/assets/libs/slugify/slugify.js\"></script>",
	})
//line internal/http/views/pages/staticpage/create.qtpl:58
	qw422016.N().S(`
	<script type="text/javascript">
		toastr.options.closeButton = true;
		toastr.options.progressBar = true;

		const trans = {};

		`)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`function getFormData($form) {
    var formData = $form.serializeArray()
        .reduce(function (json, { name, value }) {
            json[name] = value;
            return json;
        }, {});

    return {
        title: formData.title || '',
        slug: formData.slug || '',
        sortOrder: parseInt(formData.sortOrder) || 0,
        content: CKEDITOR.instances.content.getData(),
        pageType: parseInt(formData.pageType) || 0,
        seo: {
            metaTitle: formData.metaTitle || '',
            metaDescription: formData.metaDescription || '',
            metaKeywords: formData.metaKeywords || '',
            schema: formData.schema || '',
        },
        adsPlatform: parseInt(formData.adsPlatform) || 0,
        status: parseInt(formData.status) || 0
    }
}

$(function () {
    CKEDITOR.replace('content', {
        toolbarGroups: [
            { name: 'document', groups: ['mode', 'document', 'doctools'] },
            { name: 'clipboard', groups: ['clipboard', 'undo'] },
            { name: 'editing', groups: ['find', 'selection', 'spellchecker', 'editing'] },
            { name: 'forms', groups: ['forms'] },
            '/',
            { name: 'basicstyles', groups: ['basicstyles', 'cleanup'] },
            { name: 'paragraph', groups: ['list', 'indent', 'blocks', 'align', 'bidi', 'paragraph'] },
            { name: 'links', groups: ['links'] },
            { name: 'insert', groups: ['insert'] },
            '/',
            { name: 'styles', groups: ['styles'] },
            { name: 'colors', groups: ['colors'] },
            { name: 'tools', groups: ['tools'] },
            { name: 'others', groups: ['others'] },
            { name: 'about', groups: ['about'] }
        ],
        removeButtons: 'Save,NewPage,Templates,PasteText,PasteFromWord,ImageButton,Button,Select,Textarea,TextField,Form,Checkbox,Radio,HiddenField,CopyFormatting,RemoveFormat,Subscript,Language,BidiRtl,BidiLtr,Flash,PageBreak,Iframe,Font,ShowBlocks,About',
        filebrowserBrowseUrl: '/media/file-manager?sf=/content/page',
        filebrowserUploadUrl: '/media/editor-upload-file?sf=/content/page',
        height: '500px',
        on: {
            instanceReady: function () {
                const dtd = CKEDITOR.dtd;
    
                for ( var e in CKEDITOR.tools.extend( {}, 
                    dtd.$block, 
                    dtd.$listItem, 
                    dtd.$tableContent ) 
                ) {
                    this.dataProcessor.writer.setRules( e, {
                        indent: false,
                        breakBeforeOpen: false,
                        breakAfterOpen: false,
                        breakBeforeClose: false,
                        breakAfterClose: false
                    });
                }
            }
        }
    });

    $('#static-page-form .status-selection').select2({
        width: '100%',
        allowClear: false,
        minimumResultsForSearch: Infinity,
        placeholder: 'Select status',
        dropdownParent: $('#static-page-form'),
        ajax: {
            url: `)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`${config.apiAddress}/v1/common/statuses`)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`,
            headers: {
                'Authorization': `)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`Bearer ${getAccessToken()}`)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`,
            },
            delay: 300,
            data: function (params) {
                var query = {
                    name: params.term,
                }

                return query;
            },
            processResults: function (res) {
                return {
                    results: res.data
                };
            }
        },
        escapeMarkup: function (markup) {
            return markup;
        },
        templateResult: function (data) {
            return data.text;
        },
        templateSelection: function (data) {
            return data.text;
        }
    });

    $('#static-page-form .page-type-selection').select2({
        width: '100%',
        allowClear: false,
        minimumResultsForSearch: Infinity,
        placeholder: 'Select page type',
        dropdownParent: $('#static-page-form'),
        ajax: {
            url: `)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`${config.apiAddress}/v1/common/pageTypes`)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`,
            headers: {
                'Authorization': `)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`Bearer ${getAccessToken()}`)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`,
            },
            delay: 300,
            data: function (params) {
                var query = {
                    name: params.term,
                }

                return query;
            },
            processResults: function (res) {
                return {
                    results: res.data
                };
            }
        },
        escapeMarkup: function (markup) {
            return markup;
        },
        templateResult: function (data) {
            return data.text;
        },
        templateSelection: function (data) {
            return data.text;
        }
    });

    $('#static-page-form .ads-platform-selection').select2({
        width: '100%',
        allowClear: false,
        minimumResultsForSearch: Infinity,
        placeholder: 'Select Ads Platform',
        dropdownParent: $('#static-page-form'),
        ajax: {
            url: `)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`${config.apiAddress}/v1/common/adsPlatforms`)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`,
            headers: {
                'Authorization': `)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`Bearer ${getAccessToken()}`)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`,
            },
            delay: 300,
            data: function (params) {
                var query = {
                    name: params.term,
                }

                return query;
            },
            processResults: function (res) {
                return {
                    results: res.data
                };
            }
        },
        escapeMarkup: function (markup) {
            return markup;
        },
        templateResult: function (data) {
            return data.text;
        },
        templateSelection: function (data) {
            return data.text;
        }
    });
});`)
//line internal/http/views/pages/staticpage/create.qtpl:65
	qw422016.N().S(`
		`)
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S(`$(function () {
    $('#static-page-form.form-create').submit(function (event) {
        event.preventDefault();
        const formData = getFormData($(this));
    
        $.ajax({
            type: 'POST',
            url: `)
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S(`${config.apiAddress}/v1/staticPages/create`)
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S(`,
            authRequired: true,          // 👈 marks this request for interception
            xhrFields: { withCredentials: true },
            crossDomain: true,
            data: JSON.stringify(formData),
            success: function (data) {
                toastr['success'](`)
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S(`A new page was created successfully!`)
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S(`);
                window.location.replace('/pages');
            },
            error: function (xhr, status, error) {
                const resJson = xhr.responseJSON || {};
                const errs = resJson.errs || {};
                $('#page-form').find('input[name], select[name], textarea[name]').each(function () {
                    const name = $(this).attr('name');
                    const errMsg = errs[name];
                    if (errMsg && errMsg != '') {
                        addFieldError($(this), errMsg);
                    }
                });
                toastr['error'](resJson.message || `)
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S(`An error occurred!`)
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S(`);
            },
            contentType: 'application/json',
            dataType: 'json'
        });
    
        return false;
    });
});`)
//line internal/http/views/pages/staticpage/create.qtpl:66
	qw422016.N().S(`
	</script>
`)
//line internal/http/views/pages/staticpage/create.qtpl:68
}

//line internal/http/views/pages/staticpage/create.qtpl:68
func (p *Create) WriteScript(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:68
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/create.qtpl:68
	p.StreamScript(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:68
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:68
}

//line internal/http/views/pages/staticpage/create.qtpl:68
func (p *Create) Script() string {
//line internal/http/views/pages/staticpage/create.qtpl:68
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/create.qtpl:68
	p.WriteScript(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:68
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/create.qtpl:68
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:68
	return qs422016
//line internal/http/views/pages/staticpage/create.qtpl:68
}

//line internal/http/views/pages/staticpage/create.qtpl:71
func (p *Create) StreamContent(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:71
	qw422016.N().S(`<div class="pcoded-content"><div class="page-header card"><div class="row align-items-end"><div class="col-lg-8"><div class="page-header-title"><i class="feather icon-home bg-c-blue"></i><div class="d-inline"><h5>`)
//line internal/http/views/pages/staticpage/create.qtpl:79
	qw422016.E().S(bootstrap.Translator.T(p.Lang, "CREATE", nil))
//line internal/http/views/pages/staticpage/create.qtpl:79
	qw422016.N().S(`</h5><span class="icofont icofont-dog"></span></div></div></div><div class="col-lg-4"><div class="page-header-breadcrumb"><ul class=" breadcrumb breadcrumb-title"><li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i>`)
//line internal/http/views/pages/staticpage/create.qtpl:88
	qw422016.N().S(` `)
//line internal/http/views/pages/staticpage/create.qtpl:88
	qw422016.E().S(bootstrap.Translator.T(p.Lang, "DASHBOARD", nil))
//line internal/http/views/pages/staticpage/create.qtpl:88
	qw422016.N().S(`</a></li><li class="breadcrumb-item"><a href="/pages">`)
//line internal/http/views/pages/staticpage/create.qtpl:90
	qw422016.E().S(bootstrap.Translator.T(p.Lang, "STATIC_PAGES", nil))
//line internal/http/views/pages/staticpage/create.qtpl:90
	qw422016.N().S(`</a></li><li class="breadcrumb-item"><a href="#!">`)
//line internal/http/views/pages/staticpage/create.qtpl:91
	qw422016.E().S(bootstrap.Translator.T(p.Lang, "CREATE", nil))
//line internal/http/views/pages/staticpage/create.qtpl:91
	qw422016.N().S(`</a></li></ul></div></div></div></div><div class="pcoded-inner-content"><div class="main-body"><div class="page-wrapper"><div class="page-body"><div class="row"><div class="col-md-12 col-xl-12"><div class="card sale-card"><div class="card-block">`)
//line internal/http/views/pages/staticpage/create.qtpl:105
	partials.StreamForm(qw422016, nil)
//line internal/http/views/pages/staticpage/create.qtpl:105
	qw422016.N().S(`</div></div></div></div></div></div></div></div></div>`)
//line internal/http/views/pages/staticpage/create.qtpl:115
}

//line internal/http/views/pages/staticpage/create.qtpl:115
func (p *Create) WriteContent(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/create.qtpl:115
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/create.qtpl:115
	p.StreamContent(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:115
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/create.qtpl:115
}

//line internal/http/views/pages/staticpage/create.qtpl:115
func (p *Create) Content() string {
//line internal/http/views/pages/staticpage/create.qtpl:115
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/create.qtpl:115
	p.WriteContent(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:115
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/create.qtpl:115
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/create.qtpl:115
	return qs422016
//line internal/http/views/pages/staticpage/create.qtpl:115
}
