// Code generated by qtc from "list.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/http/views/pages/staticpage/list.qtpl:1
package staticpage

//line internal/http/views/pages/staticpage/list.qtpl:1
import (
	"cms/internal/bootstrap"
	"cms/internal/http/views/layout"
	"cms/internal/http/views/pages/staticpage/partials"
	"shared/models/commonmodel"
)

//line internal/http/views/pages/staticpage/list.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/http/views/pages/staticpage/list.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/http/views/pages/staticpage/list.qtpl:9
type List struct {
	layout.BasePage
}

//line internal/http/views/pages/staticpage/list.qtpl:15
func (p *List) streamgetSEOTitle(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:15
	qw422016.N().S(`Page List`)
//line internal/http/views/pages/staticpage/list.qtpl:17
}

//line internal/http/views/pages/staticpage/list.qtpl:17
func (p *List) writegetSEOTitle(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/list.qtpl:17
	p.streamgetSEOTitle(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:17
}

//line internal/http/views/pages/staticpage/list.qtpl:17
func (p *List) getSEOTitle() string {
//line internal/http/views/pages/staticpage/list.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/list.qtpl:17
	p.writegetSEOTitle(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:17
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/list.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:17
	return qs422016
//line internal/http/views/pages/staticpage/list.qtpl:17
}

//line internal/http/views/pages/staticpage/list.qtpl:21
func (p *List) streamgetSEODescription(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:21
	qw422016.N().S(`This is seo desc`)
//line internal/http/views/pages/staticpage/list.qtpl:23
}

//line internal/http/views/pages/staticpage/list.qtpl:23
func (p *List) writegetSEODescription(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/list.qtpl:23
	p.streamgetSEODescription(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:23
}

//line internal/http/views/pages/staticpage/list.qtpl:23
func (p *List) getSEODescription() string {
//line internal/http/views/pages/staticpage/list.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/list.qtpl:23
	p.writegetSEODescription(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:23
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/list.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:23
	return qs422016
//line internal/http/views/pages/staticpage/list.qtpl:23
}

//line internal/http/views/pages/staticpage/list.qtpl:27
func (p *List) streamgetSEOKeywords(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:27
	qw422016.N().S(`This is seo keyword`)
//line internal/http/views/pages/staticpage/list.qtpl:29
}

//line internal/http/views/pages/staticpage/list.qtpl:29
func (p *List) writegetSEOKeywords(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/list.qtpl:29
	p.streamgetSEOKeywords(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:29
}

//line internal/http/views/pages/staticpage/list.qtpl:29
func (p *List) getSEOKeywords() string {
//line internal/http/views/pages/staticpage/list.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/list.qtpl:29
	p.writegetSEOKeywords(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:29
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/list.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:29
	return qs422016
//line internal/http/views/pages/staticpage/list.qtpl:29
}

//line internal/http/views/pages/staticpage/list.qtpl:32
func (p *List) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:32
	qw422016.N().S(p.getSEOTitle())
//line internal/http/views/pages/staticpage/list.qtpl:32
}

//line internal/http/views/pages/staticpage/list.qtpl:32
func (p *List) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/list.qtpl:32
	p.StreamTitle(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:32
}

//line internal/http/views/pages/staticpage/list.qtpl:32
func (p *List) Title() string {
//line internal/http/views/pages/staticpage/list.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/list.qtpl:32
	p.WriteTitle(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:32
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/list.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:32
	return qs422016
//line internal/http/views/pages/staticpage/list.qtpl:32
}

//line internal/http/views/pages/staticpage/list.qtpl:34
func (p *List) StreamSEO(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:34
	qw422016.N().S(`
	`)
//line internal/http/views/pages/staticpage/list.qtpl:35
	p.BasePage.StreamSEO(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:35
	qw422016.N().S(`
	<meta name="title" content="`)
//line internal/http/views/pages/staticpage/list.qtpl:36
	qw422016.N().S(p.getSEOTitle())
//line internal/http/views/pages/staticpage/list.qtpl:36
	qw422016.N().S(`">
`)
//line internal/http/views/pages/staticpage/list.qtpl:37
}

//line internal/http/views/pages/staticpage/list.qtpl:37
func (p *List) WriteSEO(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/list.qtpl:37
	p.StreamSEO(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:37
}

//line internal/http/views/pages/staticpage/list.qtpl:37
func (p *List) SEO() string {
//line internal/http/views/pages/staticpage/list.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/list.qtpl:37
	p.WriteSEO(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:37
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/list.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:37
	return qs422016
//line internal/http/views/pages/staticpage/list.qtpl:37
}

//line internal/http/views/pages/staticpage/list.qtpl:40
func (p *List) StreamCSS(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:41
	p.BasePage.StreamCSS(qw422016, []string{
		"<link rel=\"stylesheet\" href=\"/assets/libs/bootstrap-table/bootstrap-table.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/bootstrap-table/extensions/fixed-columns/bootstrap-table-fixed-columns.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/select2/css/select2.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/toastr/toastr.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/sweetalert2/sweetalert2.min.css\">",
		"<link rel=\"stylesheet\" href=\"/assets/libs/icheck/skins/square/green.css\">",
	})
//line internal/http/views/pages/staticpage/list.qtpl:49
}

//line internal/http/views/pages/staticpage/list.qtpl:49
func (p *List) WriteCSS(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:49
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/list.qtpl:49
	p.StreamCSS(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:49
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:49
}

//line internal/http/views/pages/staticpage/list.qtpl:49
func (p *List) CSS() string {
//line internal/http/views/pages/staticpage/list.qtpl:49
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/list.qtpl:49
	p.WriteCSS(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:49
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/list.qtpl:49
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:49
	return qs422016
//line internal/http/views/pages/staticpage/list.qtpl:49
}

//line internal/http/views/pages/staticpage/list.qtpl:52
func (p *List) StreamScript(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:52
	qw422016.N().S(`
	`)
//line internal/http/views/pages/staticpage/list.qtpl:54
	statusList := make([]*commonmodel.StatusItem, len(bootstrap.StatusItems))
	for i := 0; i < len(bootstrap.StatusItems); i++ {
		statusList[i] = &commonmodel.StatusItem{
			Name:  bootstrap.Translator.T(p.Lang(), bootstrap.StatusItems[i].Name, nil),
			Value: bootstrap.StatusItems[i].Value,
		}
	}

	pageTypeList := make([]*commonmodel.PageTypeItem, len(bootstrap.PageTypeItems))
	for i := 0; i < len(bootstrap.PageTypeItems); i++ {
		pageTypeList[i] = &commonmodel.PageTypeItem{
			Name:  bootstrap.Translator.T(p.Lang(), bootstrap.PageTypeItems[i].Name, nil),
			Value: bootstrap.PageTypeItems[i].Value,
		}
	}

	statusListJson, _ := bootstrap.JSON.MarshalToString(statusList)
	pageTypeListJson, _ := bootstrap.JSON.MarshalToString(pageTypeList)

//line internal/http/views/pages/staticpage/list.qtpl:72
	qw422016.N().S(`
	`)
//line internal/http/views/pages/staticpage/list.qtpl:73
	p.BasePage.StreamScript(qw422016, []string{
		"<script src=\"/assets/libs/bootstrap-table/bootstrap-table.min.js\"></script>",
		"<script src=\"/assets/libs/bootstrap-table/extensions/fixed-columns/bootstrap-table-fixed-columns.min.js\"></script>",
		"<script src=\"/assets/libs/select2/js/select2.min.js\"></script>",
		"<script src=\"/assets/libs/toastr/toastr.min.js\"></script>",
		"<script src=\"/assets/libs/sweetalert2/sweetalert2.min.js\"></script>",
		"<script src=\"/assets/libs/moment/moment.min.js\"></script>",
		"<script src=\"/assets/libs/icheck/icheck.min.js\"></script>",
	})
//line internal/http/views/pages/staticpage/list.qtpl:81
	qw422016.N().S(`
	<script type="text/javascript">
		toastr.options.closeButton = true;
		toastr.options.progressBar = true;

		const statuses = `)
//line internal/http/views/pages/staticpage/list.qtpl:86
	qw422016.N().S(statusListJson)
//line internal/http/views/pages/staticpage/list.qtpl:86
	qw422016.N().S(`;
		const pageTypes = `)
//line internal/http/views/pages/staticpage/list.qtpl:87
	qw422016.N().S(pageTypeListJson)
//line internal/http/views/pages/staticpage/list.qtpl:87
	qw422016.N().S(`;

		const trans = {};
		
		`)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`$(function () {
    initTableFilters();

    $('#filter .status-selection').select2({
        width: '100%',
        allowClear: true,
        minimumResultsForSearch: Infinity,
        placeholder: 'Select status',
        dropdownParent: $('#filter'),
        ajax: {
            url: `)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`${config.apiAddress}/v1/common/statuses`)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`,
            headers: {
                'Authorization': `)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`Bearer ${getAccessToken()}`)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`,
            },
            delay: 300,
            data: function (params) {
                var query = {
                    name: params.term,
                }
    
                return query;
            },
            processResults: function (res) {
                return {
                    results: res.data
                };
            }
        },
        escapeMarkup: function (markup) {
            return markup;
        },
        templateResult: function (data) {
            return data.text;
        },
        templateSelection: function (data) {
            return data.text;
        }
    });

    const selectedStatus = parseInt($('#filter .status-selection').val());
    if (selectedStatus >= 0) {
        $.ajax({
            type: 'GET',
            url: `)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`${config.apiAddress}/v1/common/statuses`)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`,
            authRequired: true,          // 👈 marks this request for interception
            xhrFields: { withCredentials: true },
            crossDomain: true,
            success: function (res) {
                const data = res && res.data || [];
                const selectedItem = data.find(x => x.id === selectedStatus);
                if (selectedItem) {
                    $('#filter .status-selection').empty().append(`)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`<option value="${selectedItem.id}" selected>${selectedItem.text}</option>`)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`).trigger('change');
                }
            },
            error: function (xhr, status, error) {
                const message = (xhr.responseJSON || {}).message || `)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`Failed to get page status. Please contact admin.`)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`;
                toastr['error'](message);
            },
            contentType: 'application/json',
            dataType: 'json'
        });
    } else {
        $('#filter .status-selection').empty().trigger('change');
    }
});`)
//line internal/http/views/pages/staticpage/list.qtpl:91
	qw422016.N().S(`
		`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`const DEFAULT_PAGE_NUMBER = 1;
const DEFAULT_PAGE_SIZE = 10;

var $table = $('#static-page-list');
var $delete = $('#delete');
var $applyFilter = $('#apply-filter');
var selections = [];

let pageNumber = DEFAULT_PAGE_NUMBER;
let pageSize = DEFAULT_PAGE_SIZE;

function responseHandler(res) {
    $.each(res.data, function (i, row) {
        row.state = $.inArray(row.id, selections) !== -1
    });
    return {
        rows: res.data,
        total: res.total
    };
}

function operateFormatter(value, row, index) {
    return [
        `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`<a class="table-action-item update" href="/staticPages/${row.id}/update" title="Update">
            <i class="fa fa-edit"></i>
        </a>`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`
    ].join('');
}

window.operateEvents = {
    'click .delete': function (e, value, row, index) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                deletePages([row.id]);
            }
        });
    }
}

function initTable() {
    const urlParams = getUrlParams();
    const limit = parseInt(urlParams['limit']);
    const offset = parseInt(urlParams['offset']);

    if (limit > 0) {
        pageNumber = Math.floor(offset / limit) + 1;
    }

    if (limit > 0) {
        pageSize = limit;
    }

    $table.bootstrapTable('destroy').bootstrapTable({
        ajaxOptions: function () {
            return {
                authRequired: true,
                xhrFields: { withCredentials: true },
                crossDomain: true
            };
        },
        formatLoadingMessage: function () {
            return '';
        },
        pageNumber: pageNumber,
        pageSize: pageSize,
        fixedColumns: true,
        fixedNumber: 1,
        fixedRightNumber: 1,
        columns: [
            {
                field: 'state',
                checkbox: true,
                align: 'center',
                valign: 'middle'
            }, {
                field: 'id',
                title: 'ID',
                sortable: true,
                align: 'center',
                valign: 'middle'
            }, {
                field: 'title',
                title: trans.TITLE || 'Title',
            }, {
                field: 'slug',
                title: trans.SLUG || 'Slug',
            }, {
                field: 'sortOrder',
                title: trans.SORT_ORDER || 'Sort Order',
            }, {
                field: 'pageType',
                title: trans.PAGE_TYPE || 'pageType',
                formatter: function (value, row, index) {
                    const optionsHtml = pageTypes.map(st => {
                        const selected = row.pageType === st.value ? 'selected' : '';
                        return `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`<option value="${st.value}" ${selected}>${st.name}</option>`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`;
                    }).join('');

                    return `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`
                        <select class="table-field-page-type" onchange="updatePageType(${row.id}, this.value)" disabled>
                            ${optionsHtml}
                        </select>
                    `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`;
                }
            }, {
                field: 'status',
                title: trans.STATUS || 'Status',
                formatter: function (value, row, index) {
                    const optionsHtml = statuses.map(st => {
                        const selected = row.status === st.value ? 'selected' : '';
                        return `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`<option value="${st.value}" ${selected}>${st.name}</option>`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`;
                    }).join('');

                    return `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`
                        <select class="table-field-status" onchange="updateStatus(${row.id}, this.value)">
                            ${optionsHtml}
                        </select>
                    `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`;
                }
            }, {
                field: 'createdAt',
                title: trans.CREATED_UPDATED_AT || 'Created/Updated At',
                sortable: false,
                editable: false,
                valign: 'middle',
                align: 'center',
                formatter: function (value, row, index) {
                    return `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`${moment(row.createdAt).format('DD-MM-YYYY HH:mm:ss')}<br/>${moment(row.updatedAt).format('DD-MM-YYYY HH:mm:ss')}`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`;
                }
            }, {
                field: 'createdBy',
                title: trans.CREATED_UPDATED_BY || 'Created/Updated By',
                sortable: false,
                editable: false,
                valign: 'middle',
                align: 'center',
                formatter: function (value, row, index) {
                    return `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`${(row.createdByUser || {}).userName}<br/>${(row.updatedByUser || {}).userName}`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`;
                }
            }, {
                field: 'operate',
                title: trans.ACTIONS || 'Actions',
                align: 'center',
                clickToSelect: false,
                events: window.operateEvents,
                formatter: operateFormatter
            }
        ]
    });
    $table.on('post-body.bs.table', function (data) {
        selections = getIdSelections();
        $('#static-page-list .table-field-status').select2({
            width: '180px',
            allowClear: false,
            minimumResultsForSearch: Infinity,
            placeholder: 'Select status',
            dropdownParent: $('#static-page-list'),
        });

        $('#static-page-list .table-field-page-type').select2({
            width: '180px',
            allowClear: false,
            minimumResultsForSearch: Infinity,
            placeholder: 'Select page type',
            dropdownParent: $('#static-page-list'),
        });
    });
    $table.on('check.bs.table uncheck.bs.table ' + 'check-all.bs.table uncheck-all.bs.table', function () {
        if (!$table.bootstrapTable('getSelections').length) {
            $delete.addClass('disabled');
            $delete.prop('disabled', true);
        } else {
            $delete.removeClass('disabled');
            $delete.prop('disabled', false);
        }

        // save your data, here just save the current page
        selections = getIdSelections();
        // push or splice the selections if you want to save all data selections
    });
    $table.on('all.bs.table', function (e, name, args) {
        // console.log(name, args)
    });
    $delete.click(function () {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                var ids = getIdSelections();
                deletePages(ids);
            }
        });
    });
}

function updateStatus(id, status) {
    const endPoint = `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`${config.apiAddress}/v1/staticPages/${id}/update`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`;
    $.ajax({
        type: 'POST',
        url: endPoint,
        authRequired: true,          // 👈 marks this request for interception
        xhrFields: { withCredentials: true },
        crossDomain: true,
        data: JSON.stringify({ status: parseInt(status, 10), fields: ['status'] }),
        success: function (data) {
            toastr['success'](`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`Updated page status successfully!`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`);
        },
        error: function (xhr, status, error) {
            const message = (xhr.responseJSON || {}).message || `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`Failed to updated page status. Please contact admin.`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`;
            toastr['error'](message);
        },
        contentType: 'application/json',
        dataType: 'json'
    });
}

function deletePages(ids) {
    const endPoint = `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`${config.apiAddress}/v1/staticPages/delete`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`;
    $.ajax({
        type: 'DELETE',
        url: endPoint,
        authRequired: true,          // 👈 marks this request for interception
        xhrFields: { withCredentials: true },
        crossDomain: true,
        data: JSON.stringify({ ids: ids }),
        success: function (data) {
            toastr['success'](`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`Deleted admin page with ids = ${ids} successfully!`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`);
            $table.bootstrapTable('remove', {
                field: 'id',
                values: ids
            });
            if (getIdSelections().length == 0) {
                $delete.addClass('disabled');
                $delete.prop('disabled', true);
            }
        },
        error: function (xhr, status, error) {
            const message = (xhr.responseJSON || {}).message || `)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`Failed to delete page with ids = ${ids}. Please contact admin.`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S("`")
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`;
            toastr['error'](message);
        },
        contentType: 'application/json',
        dataType: 'json'
    });
}

$(function () {
    initTable();

    $applyFilter.click(function () {
        const urlParams = getUrlParams();
        const tableOptions = $table.bootstrapTable('getOptions');
        var sortName = tableOptions.sortName;
        var sortOrder = tableOptions.sortOrder;
        const limit = parseInt(urlParams['limit']);
        const offset = parseInt(urlParams['offset']);

        if (urlParams['sort']) {
            const sortArr = urlParams['sort'].split('.');
            if (sortArr.length == 2) {
                sortName = sortArr[0];
                sortOrder = sortArr[1];
            }
        }

        if (limit > 0) {
            pageNumber = Math.floor(offset / limit) + 1;
        }
        $table.bootstrapTable('refreshOptions', {
            pageNumber: pageNumber,
            sortName: sortName,
            sortOrder: sortOrder
        });
    });

    $('.reset-filter-onchange').change(function () {
        pageNumber = 1;
        setToFirstPage();
    });
})`)
//line internal/http/views/pages/staticpage/list.qtpl:92
	qw422016.N().S(`
	</script>
`)
//line internal/http/views/pages/staticpage/list.qtpl:94
}

//line internal/http/views/pages/staticpage/list.qtpl:94
func (p *List) WriteScript(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:94
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/list.qtpl:94
	p.StreamScript(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:94
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:94
}

//line internal/http/views/pages/staticpage/list.qtpl:94
func (p *List) Script() string {
//line internal/http/views/pages/staticpage/list.qtpl:94
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/list.qtpl:94
	p.WriteScript(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:94
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/list.qtpl:94
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:94
	return qs422016
//line internal/http/views/pages/staticpage/list.qtpl:94
}

//line internal/http/views/pages/staticpage/list.qtpl:97
func (p *List) StreamContent(qw422016 *qt422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:97
	qw422016.N().S(`<div class="pcoded-content"><div class="page-header card"><div class="row align-items-end"><div class="col-lg-8"><div class="page-header-title"><i class="feather icon-home bg-c-blue"></i><div class="d-inline"><h5>`)
//line internal/http/views/pages/staticpage/list.qtpl:105
	qw422016.E().S(bootstrap.Translator.T(p.Lang(), "STATIC_PAGES", nil))
//line internal/http/views/pages/staticpage/list.qtpl:105
	qw422016.N().S(`</h5><span class="icofont icofont-dog"></span></div></div></div><div class="col-lg-4"><div class="page-header-breadcrumb"><ul class=" breadcrumb breadcrumb-title"><li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i>`)
//line internal/http/views/pages/staticpage/list.qtpl:114
	qw422016.N().S(` `)
//line internal/http/views/pages/staticpage/list.qtpl:114
	qw422016.E().S(bootstrap.Translator.T(p.Lang(), "DASHBOARD", nil))
//line internal/http/views/pages/staticpage/list.qtpl:114
	qw422016.N().S(`</a></li><li class="breadcrumb-item"><a href="#!">`)
//line internal/http/views/pages/staticpage/list.qtpl:116
	qw422016.E().S(bootstrap.Translator.T(p.Lang(), "STATIC_PAGES", nil))
//line internal/http/views/pages/staticpage/list.qtpl:116
	qw422016.N().S(`</a></li></ul></div></div></div></div><div class="pcoded-inner-content"><div class="main-body"><div class="page-wrapper"><div class="page-body"><div class="row"><div class="col-md-12 col-xl-12"><div class="card sale-card"><div class="card-header"><h5 id="toolbar"><div class="ml-n1 mr-n1"><a class="btn waves-effect waves-light btn-success m-1" href="/staticPages/create"><i class="icofont icofont-plus"></i>`)
//line internal/http/views/pages/staticpage/list.qtpl:133
	qw422016.E().S(bootstrap.Translator.T(p.Lang(), "CREATE", nil))
//line internal/http/views/pages/staticpage/list.qtpl:133
	qw422016.N().S(`</a><button class="btn waves-effect waves-light btn-primary m-1" type="button" data-toggle="collapse" data-target="#filter" aria-expanded="false" aria-controls="filter"><i class="icofont icofont-filter"></i>`)
//line internal/http/views/pages/staticpage/list.qtpl:136
	qw422016.E().S(bootstrap.Translator.T(p.Lang(), "FILTER", nil))
//line internal/http/views/pages/staticpage/list.qtpl:136
	qw422016.N().S(`</button><button id="delete" class="btn waves-effect waves-light btn-danger m-1 disabled" disabled><i class="icofont icofont-trash"></i>`)
//line internal/http/views/pages/staticpage/list.qtpl:139
	qw422016.E().S(bootstrap.Translator.T(p.Lang(), "DELETE", nil))
//line internal/http/views/pages/staticpage/list.qtpl:139
	qw422016.N().S(`</button></div></h5></div><div class="card-block">`)
//line internal/http/views/pages/staticpage/list.qtpl:145
	partials.StreamFilter(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:145
	qw422016.N().S(`<table id="static-page-list"data-detail-formatter="detailFormatter"data-minimum-count-columns="2"data-pagination="true"data-unique-id="id"data-id-field="id"data-page-list="[10, 25, 50, 100, all]"data-page-size="10"data-side-pagination="server"data-sort-name="createdAt"data-sort-order="desc"data-url='`)
//line internal/http/views/pages/staticpage/list.qtpl:158
	qw422016.E().S(bootstrap.SharedConfig.APIGateway.HTTPAddress)
//line internal/http/views/pages/staticpage/list.qtpl:158
	qw422016.N().S(`/v1/staticPages?useCache=false&include=createdUser,updatedUser&withTotal=true'data-query-params="queryParams"data-response-handler="responseHandler"></table></div></div></div></div></div></div></div></div></div>`)
//line internal/http/views/pages/staticpage/list.qtpl:171
}

//line internal/http/views/pages/staticpage/list.qtpl:171
func (p *List) WriteContent(qq422016 qtio422016.Writer) {
//line internal/http/views/pages/staticpage/list.qtpl:171
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/pages/staticpage/list.qtpl:171
	p.StreamContent(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:171
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/pages/staticpage/list.qtpl:171
}

//line internal/http/views/pages/staticpage/list.qtpl:171
func (p *List) Content() string {
//line internal/http/views/pages/staticpage/list.qtpl:171
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/pages/staticpage/list.qtpl:171
	p.WriteContent(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:171
	qs422016 := string(qb422016.B)
//line internal/http/views/pages/staticpage/list.qtpl:171
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/pages/staticpage/list.qtpl:171
	return qs422016
//line internal/http/views/pages/staticpage/list.qtpl:171
}
