// Code generated by qtc from "footer.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/http/views/layout/footer.qtpl:2
package layout

//line internal/http/views/layout/footer.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/http/views/layout/footer.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/http/views/layout/footer.qtpl:2
func StreamFooter(qw422016 *qt422016.Writer, p *BasePage) {
//line internal/http/views/layout/footer.qtpl:2
	qw422016.N().S(`<footer class="sticky-footer bg-white"><div class="container my-auto"><div class="copyright text-center my-auto"><span>Copyright &copy; Your Website 2021</span></div></div></footer>`)
//line internal/http/views/layout/footer.qtpl:10
}

//line internal/http/views/layout/footer.qtpl:10
func WriteFooter(qq422016 qtio422016.Writer, p *BasePage) {
//line internal/http/views/layout/footer.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/http/views/layout/footer.qtpl:10
	StreamFooter(qw422016, p)
//line internal/http/views/layout/footer.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line internal/http/views/layout/footer.qtpl:10
}

//line internal/http/views/layout/footer.qtpl:10
func Footer(p *BasePage) string {
//line internal/http/views/layout/footer.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/http/views/layout/footer.qtpl:10
	WriteFooter(qb422016, p)
//line internal/http/views/layout/footer.qtpl:10
	qs422016 := string(qb422016.B)
//line internal/http/views/layout/footer.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/http/views/layout/footer.qtpl:10
	return qs422016
//line internal/http/views/layout/footer.qtpl:10
}
